apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: webapp
  namespace: pitstop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webapp
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: auditlogservice
  namespace: pitstop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auditlogservice
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: customermanagementapi-v1
  namespace: pitstop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: customermanagementapi-v1
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: invoiceservice
  namespace: pitstop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: invoiceservice
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: notificationservice
  namespace: pitstop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notificationservice
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: timeservice
  namespace: pitstop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: timeservice
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: vehiclemanagementapi
  namespace: pitstop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vehiclemanagementapi
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: workshopmanagementapi
  namespace: pitstop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: workshopmanagementapi
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: workshopmanagementeventhandler
  namespace: pitstop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: workshopmanagementeventhandler
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50