apiVersion: apps/v1
kind: Deployment
metadata:
  name: diyservice
  namespace: pitstop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diyservice
  template:
    metadata:
      labels:
        app: diyservice
    spec:
      containers:
      - name: diyservice
        image: docker.io/0637274570/src-diyservice:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: diyservice
  namespace: pitstop
spec:
  type: NodePort
  ports:
  - port: 5001
    targetPort: 5001
    protocol: TCP
  selector:
    app: diyservice