apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-ingress
  namespace: pitstop
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: test.groep4.k8s.devops.aimsites.nl
      http:
        paths:
          - backend:
              service:
                name: webapp
                port:
                  number: 7005
            pathType: ImplementationSpecific
            path: /
  tls:
    - hosts:
        - test.groep4.k8s.devops.aimsites.nl
      secretName: letsencrypt-cert
