apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: monitoring
  labels:
    app: minio
spec:
  type: NodePort  # Verander dit van 'ClusterIP' naar 'NodePort'
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30902  # Je kunt een specifieke poort instellen of Kubernetes er een laten toewijzen
      name: api
    - port: 9001
      targetPort: 9001
      nodePort: 30901  # Je kunt een specifieke poort instellen of Kubernetes er een laten toewijzen
      name: console
  selector:
    app: minio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: monitoring
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio
          args:
            - server
            - /data
            - "--console-address"
            - ":9001"
          env:
            - name: MINIO_ROOT_USER
              value: minio
            - name: MINIO_ROOT_PASSWORD
              value: minio123
          ports:
            - containerPort: 9000
              name: api
            - containerPort: 9001
              name: console
          volumeMounts:
            - name: minio-data
              mountPath: /data
      volumes:
        - name: minio-data
          emptyDir: {}
