apiVersion: v1
kind: Service
metadata:
  name: thanos-store
  namespace: monitoring
spec:
  ports:
    - port: 10901
      targetPort: 10901
      protocol: TCP
      name: grpc
  selector:
    app: thanos-store
