apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-store
  namespace: monitoring
  labels:
    app: thanos-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-store
  template:
    metadata:
      labels:
        app: thanos-store
    spec:
      containers:
        - name: thanos-store
          image: quay.io/thanos/thanos:v0.32.2
          args:
            - store
            - "--grpc-address=0.0.0.0:10901"
            - "--http-address=0.0.0.0:10902"
            - "--data-dir=/data"
            - "--objstore.config-file=/etc/thanos/objstore.yml"
          ports:
            - containerPort: 10901
              name: grpc
            - containerPort: 10902
              name: http
          volumeMounts:
            - name: thanos-objstore-config
              mountPath: /etc/thanos
            - name: data
              mountPath: /data
      volumes:
        - name: thanos-objstore-config
          configMap:
            name: thanos-objstore-config
        - name: data
          emptyDir: {}
