apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-objstore-config
  namespace: monitoring
data:
  objstore.yml: |
    type: s3
    config:
      bucket: thanos-bucket
      endpoint: minio.monitoring.svc.cluster.local:9000
      access_key: minio
      secret_key: minio123
      insecure: true
