kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: chaoskube-rolebinding
  namespace: pitstop
subjects:
- kind: ServiceAccount
  name: chaoskube-sa
  namespace: default
roleRef:
  kind: Role
  name: chaoskube-role
  apiGroup: rbac.authorization.k8s.io
