name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build & Test
    env:
      Headless: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ./src/pitstop.sln

    - name: Build
      run: dotnet build --no-restore ./src/pitstop.sln

    - name: Test
      run: dotnet test --no-build --verbosity normal ./src/pitstop.sln

  publish:
    needs: build-and-test
    runs-on: ubuntu-latest
    name: Publish
    #if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run shell script
      run: ./RebuildAllDockerImages.ps1
      working-directory: src
      shell: pwsh

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Execute push images script
      run: ./push-images.ps1
      working-directory: src
      shell: pwsh

  deploy:
    needs: publish
    runs-on: ubuntu-latest
    name: deploy
    #if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Decode kubeconfig from Base64
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 -d > $HOME/.kube/config
      env:
        KUBECONFIG: $HOME/.kube/config

    - name: Verify Kubernetes Context
      run: kubectl config get-contexts

    - name: Use Kubernetes Context
      run: kubectl config use-context groep4

    - name: Stop Pods
      run: ./stop-all.ps1
      working-directory: src/k8s/scripts
      shell: pwsh

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Start Pods
      run: ./start-all.ps1 -nomesh
      working-directory: src/k8s/scripts
      shell: pwsh
